############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Services"
url = "service/"
weight = 3

## [[main]]
# name = "Testimonials"
# url = "testimonials/"
# weight = 5
  
[[main]]
name = "Contact"
url = "contact/"
weight = 4


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Services"
url = "service/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 7